/**
 * Email templates for partner referrals
 */

import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses'
import { EMAIL_THEME, emailMeta, escapeEmailHtml, renderEmail } from './layout'

const sesClient = new SESClient({
  region: process.env.APP_AWS_REGION || process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.APP_AWS_ACCESS_KEY_ID || process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey:
      process.env.APP_AWS_SECRET_ACCESS_KEY || process.env.AWS_SECRET_ACCESS_KEY || '',
  },
})

interface PartnerReferralEmailData {
  partnerName: string
  partnerEmail: string
  leadName: string
  leadEmail: string
  leadPhone?: string
  creditBand: string
  propertyType: string
  occupancy: string
  requestedLoanAmount?: number
  downPaymentPct: number
  termPreference: string
  contactPreference: string
  notes?: string
  referralId: string
}

/**
 * Send referral notification email to partner
 */
export async function sendPartnerReferralEmail(
  data: PartnerReferralEmailData
): Promise<boolean> {
  const fromEmail =
    process.env.APP_AWS_SES_FROM_EMAIL ||
    process.env.AWS_SES_FROM_EMAIL ||
    'noreply@betterclose.co'
  const formattedSource = /<[^>]+>/.test(fromEmail)
    ? fromEmail
    : `BetterClose <${fromEmail}>`

  const htmlBody = generatePartnerEmailHTML(data)
  const textBody = generatePartnerEmailText(data)

  const params = {
    Source: formattedSource,
    Destination: {
      ToAddresses: [data.partnerEmail],
    },
    Message: {
      Subject: {
        Data: `New Mortgage Referral - ${data.leadName}`,
        Charset: 'UTF-8',
      },
      Body: {
        Html: {
          Data: htmlBody,
          Charset: 'UTF-8',
        },
        Text: {
          Data: textBody,
          Charset: 'UTF-8',
        },
      },
    },
  }

  try {
    const command = new SendEmailCommand(params)
    await sesClient.send(command)
    return true
  } catch (error) {
    console.error('Error sending partner referral email:', error)
    return false
  }
}

function generatePartnerEmailHTML(data: PartnerReferralEmailData): string {
  // Inline table cells remain readable in email clients without CSS Grid.
  const section = (title: string, rows: [string, string][]) => `
    <h2 style="font-size:16px;line-height:24px;margin:24px 0 12px;">${escapeEmailHtml(title)}</h2>
    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="table-layout:fixed;border-collapse:collapse;">
      ${rows.map(([label, value]) => `<tr>
        <th scope="row" width="40%" align="left" valign="top" style="padding:10px 12px 10px 0;font-size:13px;line-height:20px;color:${EMAIL_THEME.muted};font-weight:600;border-bottom:1px solid ${EMAIL_THEME.border};">${escapeEmailHtml(label)}</th>
        <td valign="top" style="padding:10px 0;font-size:15px;line-height:22px;border-bottom:1px solid ${EMAIL_THEME.border};overflow-wrap:anywhere;word-break:break-word;">${escapeEmailHtml(value)}</td>
      </tr>`).join('')}
    </table>`
  return renderEmail({
    title: 'New Mortgage Referral',
    context: 'Mortgage partner',
    contentHtml: `${emailMeta(`Referral ID: ${data.referralId}`)}
    <p>Hi ${escapeEmailHtml(data.partnerName)},</p>
    <p>You have received a new mortgage referral from BetterClose. Please review the client details below and reach out according to their contact preferences.</p>
    ${section('Contact Information', [
      ['Name', data.leadName], ['Email', data.leadEmail],
      ['Phone', data.leadPhone || 'Not provided'],
      ['Preferred Contact', formatContactPreference(data.contactPreference)],
    ])}
    ${section('Loan Preferences', [
      ['Credit Band', formatCreditBand(data.creditBand)],
      ['Property Type', formatPropertyType(data.propertyType)],
      ['Occupancy', formatOccupancy(data.occupancy)],
      ['Term Preference', formatTermPreference(data.termPreference)],
      ['Loan Amount', data.requestedLoanAmount ? `$${data.requestedLoanAmount.toLocaleString()}` : 'Not specified'],
      ['Down Payment', `${data.downPaymentPct}%`],
    ])}
    ${data.notes ? `<h2 style="font-size:16px;line-height:24px;margin:24px 0 12px;">Additional Notes</h2><p>${escapeEmailHtml(data.notes)}</p>` : ''}
    <p style="margin-top:28px;">
      <strong>Next Steps:</strong><br>
      Please reach out to this client within 24 hours according to their contact preference.
      They are expecting to hear from you regarding purchase loan options.
    </p>`,
    footerHtml: "This referral was generated by BetterClose's mortgage platform.<br>If you have questions about this referral, please contact our team.",
  })
}

function generatePartnerEmailText(data: PartnerReferralEmailData): string {
  return `
New Mortgage Referral - ${data.leadName}
Referral ID: ${data.referralId}

Hi ${data.partnerName},

You have received a new mortgage referral from BetterClose.

CONTACT INFORMATION
Name: ${data.leadName}
Email: ${data.leadEmail}
Phone: ${data.leadPhone || 'Not provided'}
Preferred Contact: ${formatContactPreference(data.contactPreference)}

LOAN PREFERENCES
Credit Band: ${formatCreditBand(data.creditBand)}
Property Type: ${formatPropertyType(data.propertyType)}
Occupancy: ${formatOccupancy(data.occupancy)}
Term Preference: ${formatTermPreference(data.termPreference)}
Loan Amount: ${data.requestedLoanAmount ? `$${data.requestedLoanAmount.toLocaleString()}` : 'Not specified'}
Down Payment: ${data.downPaymentPct}%

${data.notes ? `ADDITIONAL NOTES\n${data.notes}\n` : ''}

NEXT STEPS
Please reach out to this client within 24 hours according to their contact preference.

---
This referral was generated by BetterClose's mortgage platform.
  `.trim()
}

function formatCreditBand(band: string): string {
  const bandMap: Record<string, string> = {
    excellent: 'Excellent (740+)',
    good: 'Good (670-739)',
    fair: 'Fair (580-669)',
    poor: 'Poor (<580)',
  }
  return bandMap[band] || band
}

function formatPropertyType(type: string): string {
  const typeMap: Record<string, string> = {
    single_family: 'Single Family',
    condo: 'Condominium',
    townhouse: 'Townhouse',
    multi_family: 'Multi-Family',
    manufactured: 'Manufactured',
  }
  return typeMap[type] || type
}

function formatOccupancy(occupancy: string): string {
  const occupancyMap: Record<string, string> = {
    primary: 'Primary Residence',
    secondary: 'Secondary/Vacation Home',
    investment: 'Investment Property',
  }
  return occupancyMap[occupancy] || occupancy
}

function formatTermPreference(term: string): string {
  const termMap: Record<string, string> = {
    '30_year': '30 Year Fixed',
    '15_year': '15 Year Fixed',
    '20_year': '20 Year Fixed',
    '10_year': '10 Year Fixed',
    '7_1_arm': '7/1 ARM',
    '5_1_arm': '5/1 ARM',
    arm: 'ARM',
  }
  return termMap[term] || term
}

function formatContactPreference(pref: string): string {
  const prefMap: Record<string, string> = {
    email: 'Email',
    phone: 'Phone',
    both: 'Email & Phone',
  }
  return prefMap[pref] || pref
}
